kind: wasmer.io/App.v0
name: balingasagshs
owner: cincocharlie25
package: .

env:
  APP_ENV: production
  APP_SESSION_DRIVER: database
  DB_SSL_VERIFY_SERVER_CERT: "1"
  API_ALLOWED_ORIGIN: "https://balingasagshs.wasmer.app"
  APP_PUBLIC_BASE_URL: "https://balingasagshs.wasmer.app"
  SMS_PROVIDER: "philsms"
  SMS_SENDER_NAME: "PhilSMS"
  SMS_ENDPOINT: "https://dashboard.philsms.com/api/v3/sms/send"

capabilities:
  instaboot:
    requests:
      - path: /

volumes:
  - name: storage
    mount: /app/storage
  - name: uploads
    mount: /app/assets/uploads
