[package]
name = "bshs-ams"
version = "0.1.6"
description = "Balingasag Senior High School Attendance and Academic Management System"

[dependencies]
"php/php" = "=8.3.4"

[fs]
"/app" = "."
"/config" = "config/wasmer"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080", "/app/router.php"]
env = ["PHPRC=/config/"]


