<?php
require_once __DIR__ . '/../functions/bootstrap.php';
if (empty($_SESSION['logged_in']) || ($_SESSION['role'] ?? '') !== 'principal') { header('Location: ../auth/login.php'); exit; }
$db = (new Database())->getConnection();
$search = trim((string)($_GET['search'] ?? '')); $role = trim((string)($_GET['role'] ?? '')); $dateFrom = trim((string)($_GET['date_from'] ?? '')); $dateTo = trim((string)($_GET['date_to'] ?? ''));
$allowedRoles = ['', 'principal', 'admin', 'teacher', 'student', 'parent']; if (!in_array($role, $allowedRoles, true)) { $role = ''; }
$validDate = static function (string $value): bool { if ($value === '') return true; $date = DateTime::createFromFormat('Y-m-d', $value); return $date instanceof DateTime && $date->format('Y-m-d') === $value; };
if (!$validDate($dateFrom)) $dateFrom = ''; if (!$validDate($dateTo)) $dateTo = '';
$rows = []; $loadError = '';
try {
    $where = []; $params = [];
    if ($search !== '') { $where[] = '(al.action_name LIKE ? OR al.target_type LIKE ? OR u.reference_code LIKE ? OR u.first_name LIKE ? OR u.last_name LIKE ?)'; $needle = '%' . $search . '%'; array_push($params, $needle, $needle, $needle, $needle, $needle); }
    if ($role !== '') { $where[] = 'al.actor_role = ?'; $params[] = $role; }
    if ($dateFrom !== '') { $where[] = 'al.created_at >= ?'; $params[] = $dateFrom . ' 00:00:00'; }
    if ($dateTo !== '') { $where[] = 'al.created_at <= ?'; $params[] = $dateTo . ' 23:59:59'; }
    $sql = "SELECT al.actor_role, al.action_name, al.target_type, al.target_id, al.details_json, al.created_at, u.reference_code, u.first_name, u.last_name FROM activity_logs al LEFT JOIN users u ON u.id = al.actor_user_id" . ($where ? ' WHERE ' . implode(' AND ', $where) : '') . ' ORDER BY al.created_at DESC, al.id DESC LIMIT 200';
    $stmt = $db->prepare($sql); $stmt->execute($params); $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (Throwable $e) { error_log('Principal activity log load failed.'); $loadError = 'Activity logs could not be loaded.'; }
$formatDetails = static function (?string $json): string { $data = json_decode((string)$json, true); if (!is_array($data)) return 'No additional details'; unset($data['ip_address'], $data['user_agent'], $data['password'], $data['token']); $parts = []; foreach ($data as $key => $value) { if (is_array($value)) $value = implode(', ', array_map('strval', $value)); elseif (is_bool($value)) $value = $value ? 'yes' : 'no'; elseif ($value === null) $value = 'none'; $parts[] = ucwords(str_replace('_', ' ', (string)$key)) . ': ' . (string)$value; } return $parts ? implode(' | ', $parts) : 'No additional details'; };
$current_role = 'principal'; $current_page = 'activity_logs'; $page_title = 'Activity Logs';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo htmlspecialchars($page_title); ?> - Balingasag Senior High School</title><link href="<?php echo appAssetPath('src/vendor/bootstrap/bootstrap.min.css'); ?>" rel="stylesheet"><link rel="stylesheet" href="<?php echo appAssetPath('src/vendor/bootstrap-icons/bootstrap-icons.css'); ?>"><link rel="stylesheet" href="<?php echo appAssetPath('css/main.css'); ?>"><link rel="stylesheet" href="<?php echo appAssetPath('css/role.css'); ?>"><?php echo pwaHeadHtml(); ?></head><body>
<?php include __DIR__ . '/../includes/sidebar.php'; ?><main class="main-content"><?php include __DIR__ . '/../includes/header.php'; ?><div class="page-content">
<section class="admin-hero admin-hero-compact mb-4" aria-labelledby="activity-heading"><div class="admin-hero-main"><div class="welcome-role-chip"><i class="bi bi-activity"></i><span>Read-only monitoring</span></div><h1 class="h4 mb-2" id="activity-heading">System activity logs</h1><p class="text-muted mb-0">Monitor role-aware system actions without access to login diagnostics, IP addresses, credentials, or security tokens.</p></div></section>
<section class="content-card mb-4"><div class="content-card-body"><form method="get" class="row g-3 align-items-end app-responsive-filter-form"><div class="col-12 col-lg-4"><label class="form-label" for="activity-search">Search</label><input class="form-control" id="activity-search" name="search" value="<?php echo htmlspecialchars($search); ?>" placeholder="Actor, action, target, or reference"></div><div class="col-6 col-lg-2"><label class="form-label" for="activity-role">Role</label><select class="form-select" id="activity-role" name="role"><option value="">All roles</option><?php foreach (array_slice($allowedRoles, 1) as $option): ?><option value="<?php echo $option; ?>" <?php echo $role === $option ? 'selected' : ''; ?>><?php echo ucfirst($option); ?></option><?php endforeach; ?></select></div><div class="col-6 col-lg-2"><label class="form-label" for="activity-from">From</label><input class="form-control" type="date" id="activity-from" name="date_from" value="<?php echo htmlspecialchars($dateFrom); ?>"></div><div class="col-6 col-lg-2"><label class="form-label" for="activity-to">To</label><input class="form-control" type="date" id="activity-to" name="date_to" value="<?php echo htmlspecialchars($dateTo); ?>"></div><div class="col-6 col-lg-2 d-grid"><button class="btn btn-primary" type="submit"><i class="bi bi-funnel me-1"></i>Apply</button></div></form></div></section>
<?php if ($loadError !== ''): ?><div class="alert alert-danger"><?php echo htmlspecialchars($loadError); ?></div><?php endif; ?>
<section class="content-card"><div class="content-card-header"><h2 class="content-card-title">Recent system actions</h2></div><div class="content-card-body"><div class="table-responsive"><table class="table custom-table align-middle mb-0"><thead><tr><th>Actor</th><th>Action</th><th>Target</th><th>Details</th><th>Date</th></tr></thead><tbody><?php if (!$rows): ?><tr><td colspan="5"><div class="empty-state py-4">No activity matches these filters.</div></td></tr><?php endif; ?><?php foreach ($rows as $row): ?><tr><td><strong><?php echo htmlspecialchars(trim((string)$row['first_name'] . ' ' . (string)$row['last_name']) ?: 'System'); ?></strong><small class="d-block text-muted"><?php echo htmlspecialchars(ucfirst((string)$row['actor_role'])); ?><?php echo $row['reference_code'] ? ' · ' . htmlspecialchars((string)$row['reference_code']) : ''; ?></small></td><td><?php echo htmlspecialchars(ucwords(str_replace(['.', '_'], ' ', (string)$row['action_name']))); ?></td><td><?php echo htmlspecialchars(ucwords(str_replace('_', ' ', (string)$row['target_type']))); ?><?php echo $row['target_id'] ? ' #' . (int)$row['target_id'] : ''; ?></td><td><small><?php echo htmlspecialchars($formatDetails($row['details_json'])); ?></small></td><td><time datetime="<?php echo htmlspecialchars((string)$row['created_at']); ?>"><?php echo htmlspecialchars(date('M j, Y g:i A', strtotime((string)$row['created_at']))); ?></time></td></tr><?php endforeach; ?></tbody></table></div></div></section>
</div></main><?php include __DIR__ . '/../includes/footer.php'; ?>
