<?php
require_once __DIR__ . '/../functions/bootstrap.php';
if (empty($_SESSION['logged_in']) || ($_SESSION['role'] ?? '') !== 'principal') { header('Location: ../auth/login.php'); exit; }
$db = (new Database())->getConnection();
$rows = (new \BshsAms\Grade\PrincipalReportCardQuery($db))->find(['approved']);
$current_role = 'principal'; $current_page = 'released'; $page_title = 'Admin-Released Report Cards';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo htmlspecialchars($page_title); ?></title><link href="<?php echo appAssetPath('src/vendor/bootstrap/bootstrap.min.css'); ?>" rel="stylesheet"><link rel="stylesheet" href="<?php echo appAssetPath('src/vendor/bootstrap-icons/bootstrap-icons.css'); ?>"><link rel="stylesheet" href="<?php echo appAssetPath('css/main.css'); ?>"><link rel="stylesheet" href="<?php echo appAssetPath('css/role.css'); ?>"><?php echo pwaHeadHtml(); ?></head><body>
<?php include __DIR__ . '/../includes/sidebar.php'; ?><main class="main-content"><?php include __DIR__ . '/../includes/header.php'; ?><div class="page-content">
<section class="admin-hero admin-hero-compact mb-4"><div class="admin-hero-main"><div class="welcome-role-chip"><i class="bi bi-eye"></i><span>Read-only release register</span></div><h1 class="h4">Admin-released report cards</h1><p class="text-muted mb-0">These records passed Teacher submission, Principal subject verification, Adviser compilation, Principal endorsement, and Admin final release.</p></div></section>
<section class="content-card"><div class="content-card-header"><h2 class="content-card-title">Visible to students and parents</h2></div><div class="content-card-body"><div class="table-responsive"><table class="table custom-table align-middle"><thead><tr><th>Learner</th><th>Class</th><th>Period</th><th>Released by Admin</th><th>Visibility</th></tr></thead><tbody><?php if (!$rows): ?><tr><td colspan="5"><div class="empty-state py-5">No Admin-released report cards.</div></td></tr><?php endif; ?><?php foreach ($rows as $row): ?><tr><td><strong><?php echo htmlspecialchars($row['last_name'] . ', ' . $row['first_name']); ?></strong><small class="d-block text-muted"><?php echo htmlspecialchars((string)$row['reference_code']); ?></small></td><td>Grade <?php echo (int)$row['grade_level']; ?> <?php echo htmlspecialchars((string)$row['section']); ?></td><td><?php echo htmlspecialchars((string)$row['academic_year']); ?><small class="d-block"><?php echo htmlspecialchars((string)($row['semester'] ?: 'Final')); ?></small></td><td><?php echo htmlspecialchars((string)($row['reviewer_name'] ?: 'Admin')); ?><small class="d-block text-muted"><?php echo $row['reviewed_at'] ? htmlspecialchars(date('M j, Y g:i A', strtotime((string)$row['reviewed_at']))) : ''; ?></small></td><td><span class="badge text-bg-success"><i class="bi bi-eye me-1"></i>Family visible</span></td></tr><?php endforeach; ?></tbody></table></div></div></section>
</div></main><?php include __DIR__ . '/../includes/footer.php'; ?>
