<?php
require_once __DIR__ . '/../functions/bootstrap.php';
if (empty($_SESSION['logged_in']) || ($_SESSION['role'] ?? '') !== 'admin') { header('Location: ../auth/login.php'); exit; }
$db = (new Database())->getConnection();
$view = ($_GET['view'] ?? 'pending') === 'released' ? 'released' : 'pending';
$query = new \BshsAms\Grade\PrincipalReportCardQuery($db);
$rows = $query->find([$view === 'released' ? 'approved' : 'pending']);
$current_role = 'admin'; $current_page = 'report_cards'; $page_title = 'Final Report Card Release';
$csrfToken = (string)($_SESSION['csrf_token'] ?? '');
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo htmlspecialchars($page_title); ?></title><link href="<?php echo appAssetPath('src/vendor/bootstrap/bootstrap.min.css'); ?>" rel="stylesheet"><link rel="stylesheet" href="<?php echo appAssetPath('src/vendor/bootstrap-icons/bootstrap-icons.css'); ?>"><link rel="stylesheet" href="<?php echo appAssetPath('css/main.css'); ?>"><link rel="stylesheet" href="<?php echo appAssetPath('css/role.css'); ?>"><?php echo pwaHeadHtml(); ?></head><body>
<?php include __DIR__ . '/../includes/sidebar.php'; ?><main class="main-content"><?php include __DIR__ . '/../includes/header.php'; ?><div class="page-content">
<section class="admin-hero admin-hero-compact mb-4"><div class="admin-hero-main"><div class="welcome-role-chip"><i class="bi bi-patch-check"></i><span>Final release authority</span></div><h1 class="h4">Admin report-card release</h1><p class="text-muted mb-0">Release only report cards endorsed by the Principal. Family visibility begins after this decision.</p></div></section>
<div class="d-flex gap-2 mb-3"><a class="btn <?php echo $view === 'pending' ? 'btn-primary' : 'btn-outline-primary'; ?>" href="?view=pending">Awaiting release</a><a class="btn <?php echo $view === 'released' ? 'btn-primary' : 'btn-outline-primary'; ?>" href="?view=released">Released records</a></div>
<section class="content-card"><div class="content-card-header"><h2 class="content-card-title"><?php echo $view === 'pending' ? 'Principal-endorsed report cards' : 'Released report cards'; ?></h2></div><div class="content-card-body">
<div class="principal-action-bar mb-3" id="action-bar" hidden><span><strong id="selected-count">0</strong> selected</span><div class="d-flex gap-2"><?php if ($view === 'pending'): ?><button class="btn btn-success btn-sm" data-decision="approve">Release</button><button class="btn btn-danger btn-sm" data-decision="reject">Return</button><?php else: ?><button class="btn btn-warning btn-sm" data-decision="withdraw">Withdraw</button><?php endif; ?></div></div>
<div class="table-responsive"><table class="table custom-table align-middle"><thead><tr><th></th><th>Learner</th><th>Class</th><th>Period</th><th>Principal action</th><th>Status</th></tr></thead><tbody><?php if (!$rows): ?><tr><td colspan="6"><div class="empty-state py-5">No report cards found.</div></td></tr><?php endif; ?><?php foreach ($rows as $row): ?><tr><td><input class="form-check-input card-check" type="checkbox" value="<?php echo (int)$row['id']; ?>"></td><td><strong><?php echo htmlspecialchars($row['last_name'] . ', ' . $row['first_name']); ?></strong><small class="d-block text-muted"><?php echo htmlspecialchars((string)$row['reference_code']); ?></small></td><td>Grade <?php echo (int)$row['grade_level']; ?> <?php echo htmlspecialchars((string)$row['section']); ?></td><td><?php echo htmlspecialchars((string)$row['academic_year']); ?><small class="d-block"><?php echo htmlspecialchars((string)($row['semester'] ?: 'Final')); ?></small></td><td><?php echo htmlspecialchars((string)($row['reviewer_name'] ?: 'Principal')); ?><small class="d-block text-muted"><?php echo $row['reviewed_at'] ? htmlspecialchars(date('M j, Y', strtotime((string)$row['reviewed_at']))) : ''; ?></small></td><td><span class="badge text-bg-<?php echo $row['status'] === 'approved' ? 'success' : 'warning'; ?>"><?php echo $row['status'] === 'approved' ? 'Released' : 'Awaiting Admin'; ?></span></td></tr><?php endforeach; ?></tbody></table></div>
</div></section></div></main>
<div class="modal fade" id="decisionModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" id="decision-form"><div class="modal-header"><h2 class="modal-title fs-5">Confirm Admin decision</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label" for="remarks">Remarks</label><textarea class="form-control" id="remarks" maxlength="255"></textarea><div class="form-text">Required when returning or withdrawing.</div><div class="alert alert-danger mt-3" id="error" hidden></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" id="submit">Confirm</button></div></form></div></div>
<script>window.addEventListener('DOMContentLoaded',()=>{const boxes=[...document.querySelectorAll('.card-check')],bar=document.getElementById('action-bar'),count=document.getElementById('selected-count'),modal=new bootstrap.Modal(document.getElementById('decisionModal'));let decision='';const selected=()=>boxes.filter(x=>x.checked);boxes.forEach(x=>x.addEventListener('change',()=>{count.textContent=selected().length;bar.hidden=!selected().length;}));document.querySelectorAll('[data-decision]').forEach(b=>b.addEventListener('click',()=>{decision=b.dataset.decision;modal.show();}));document.getElementById('decision-form').addEventListener('submit',async e=>{e.preventDefault();const remarks=document.getElementById('remarks').value.trim(),error=document.getElementById('error');if(decision!=='approve'&&!remarks){error.textContent='Remarks are required.';error.hidden=false;return;}const body=new URLSearchParams({csrf_token:<?php echo json_encode($csrfToken); ?>,decision,remarks,report_card_ids:JSON.stringify(selected().map(x=>x.value))});const res=await fetch('admin_Report_Cards_Action.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body});const data=await res.json();if(!res.ok||!data.success){error.textContent=data.message||'Unable to save.';error.hidden=false;return;}location.reload();});});</script>
<?php include __DIR__ . '/../includes/footer.php'; ?>
